```{r kmfuncss12, cache=cacheon}

kmfunc <- function(time, event, eventmod = NULL, eventname, ymax = 1, rep = FALSE) {
  fits <- survfit(formula(paste0("Surv(", time, ",", event, "== 'Yes') ~ sos_lm_arni14")),
    data = rsdata %>% filter(shf_location == "In-patient")
  )
  fitsm <- survfit(formula(paste0("Surv(", time, ",", event, "== 'Yes') ~ sos_lm_arni14")),
    data = rsdata %>% filter(!is.na(parpop1))
  )

  if (!rep) {
    # cox model
    mod <- coxph(formula(paste0("Surv(", time, ",", event, "=='Yes') ~ sos_lm_arni14")),
      data = rsdata %>% filter(shf_location == "In-patient")
    )
    smod <- summary(mod)
    hrprintcrude <- paste0(
      fn(smod$conf.int[1, 1], dig = 2),
      " (", fn(smod$conf.int[1, 3], dig = 2),
      "-", fn(smod$conf.int[1, 4], dig = 2), "), ",
      fn(smod$coef[1, 5], dig = 3, p = TRUE)
    )
    # matched
    mod <- coxph(formula(paste0("Surv(", time, ",", event, "=='Yes') ~ sos_lm_arni14 + frailty.gaussian(parpop1)")),
      data = rsdata %>% filter(!is.na(parpop1))
    )
    se <- sqrt(vcov(mod)[1])

    hrprintadj <- paste0(
      fn(exp(mod$coefficients[1]), dig = 2),
      " (", fn(exp(mod$coefficients[1] - global_z05 * se), dig = 2),
      "-", fn(exp(mod$coefficients[1] + global_z05 * se), dig = 2), "), ",
      fn((1 - pnorm(abs(mod$coeff[1] / se))) * 2, dig = 3, p = TRUE)
    )
  }
  if (rep) {
    mod <- summary(glm.nb(formula(paste0(eventmod, " ~ sos_lm_arni14 + offset(log(sos_outtime_death))")),
      data = rsdata %>% filter(sos_outtime_death > 0 & shf_location == "In-patient")
    ))

    hrprintcrude <- paste0(
      fn(exp(mod$coefficients[2, 1]), dig = 2),
      " (", fn(exp(mod$coefficients[2, 1] - global_z05 * mod$coefficients[2, 2]), dig = 2),
      "-", fn(exp(mod$coefficients[2, 1] + global_z05 * mod$coefficients[2, 2]), dig = 2), "), ",
      fn(mod$coefficients[2, 4], dig = 3, p = TRUE)
    )

    # matched
    mod <- summary(lme4::glmer.nb(formula(paste0(eventmod, " ~
                                                     sos_lm_arni14 + offset(log(sos_outtime_death)) + (1 | parpop1)")),
      data = rsdata %>% filter(!is.na(parpop1))
    ))
    se <- sqrt(vcov(mod)[1])

    hrprintadj <- paste0(
      fn(exp(mod$coefficients[2, 1]), dig = 2),
      " (", fn(exp(mod$coefficients[2, 1] - global_z05 * mod$coefficients[2, 2]), dig = 2),
      "-", fn(exp(mod$coefficients[2, 1] + global_z05 * mod$coefficients[2, 2]), dig = 2), "), ",
      fn(mod$coefficients[2, 4], dig = 3, p = TRUE)
    )

    fitsr <- mcf(formula(paste0("Recur(sos_outtime, lopnr, ", event, " == 1) ~ sos_lm_arni14")),
      data = rsdatarec %>% filter(shf_location == "In-patient")
    )
    fitsrm <- mcf(formula(paste0("Recur(sos_outtime, lopnr, ", event, " == 1) ~ sos_lm_arni14")),
      data = rsdatarec %>% filter(!is.na(parpop1))
    )
  }

  # c(bottom, left, top, right)
  cexmy <- 1.2
  par(mar = c(8.5, 11, 1, 1.5) + 0.1)

  if (!rep) {
    plots <- plot(fits,
      fun = "event",
      ylab = paste0(eventname, " (%)"),
      yscale = 100,
      xscale = 365,
      col = global_cols[c(1, 1)],
      mark.time = FALSE,
      bty = "n",
      xlim = c(0, 365 * 4),
      ylim = c(0, ymax + 0.05),
      xlab = "Follow-up (years)",
      cex.lab = cexmy,
      axes = F,
      lwd = 2.5,
      lty = c(3, 1),
      xaxs = "i", yaxs = "i"
    )
    lines(fitsm,
      fun = "event",
      yscale = 100,
      xscale = 365,
      col = global_cols[c(4, 4)],
      mark.time = FALSE,
      conf.int = FALSE,
      lwd = 2.5,
      lty = c(3, 1),
      xaxs = "i", yaxs = "i"
    )

    axis(2, seq(0, ymax + 0.05, 0.05), c(seq(0, ymax * 100, 5), 100), las = 2, cex.axis = cexmy)
    plotrix::axis.break(2, ymax + 0.025, style = "slash")
  }

  if (rep) {
    plot(fitsr@MCF$time[fitsr@MCF["sos_lm_arni14"] == "No"],
      fitsr@MCF$MCF[fitsr@MCF["sos_lm_arni14"] == "No"],
      type = "l",
      ylab = paste0("Mean cumulative ", eventname, " (per 100 patients)"),
      col = global_cols[1],
      xlim = c(0, 365 * 4),
      ylim = c(0, ymax + 0.05),
      xlab = "Follow-up (years)",
      cex.lab = cexmy,
      axes = F,
      lwd = 2.5,
      lty = 3,
      xaxs = "i", yaxs = "i"
    )
    lines(fitsr@MCF$time[fitsr@MCF["sos_lm_arni14"] == "Yes"],
      fitsr@MCF$MCF[fitsr@MCF["sos_lm_arni14"] == "Yes"],
      col = global_cols[1],
      lwd = 2.5,
      lty = 1
    )
    lines(fitsrm@MCF$time[fitsrm@MCF["sos_lm_arni14"] == "No"],
      fitsrm@MCF$MCF[fitsrm@MCF["sos_lm_arni14"] == "No"],
      col = global_cols[4],
      lwd = 2.5,
      lty = 3
    )
    lines(fitsrm@MCF$time[fitsrm@MCF["sos_lm_arni14"] == "Yes"],
      fitsrm@MCF$MCF[fitsrm@MCF["sos_lm_arni14"] == "Yes"],
      col = global_cols[4],
      lwd = 2.5,
      lty = 1
    )

    axis(2, seq(0, ymax, 0.5), seq(0, ymax * 100, 50), las = 2, cex.axis = cexmy)
  }

  axis(1, at = seq(0, 4) * 365, seq(0, 4), cex.axis = cexmy)

  levs <- c("No ARNi (crude)", "ARNi (crude)", "No ARNi (adjusted)", "ARNi (adjusted)")

  legend(
    x = 0.5, y = ymax + 0.05, bty = "n", c("", levs),
    col = c("white", global_cols[c(1, 1, 4, 4)]), cex = cexmy, lwd = 2.5, lty = c(1, 3, 1, 3, 1),
    text.col = c("white", global_cols[c(1, 1, 4, 4)])
  )
  if (rep) {rname <- "RR"}
  if (!rep) {rname <- "HR"}
  legend(
    x = 2.35 * 365, y = ymax + 0.05, c(paste0(rname, " (95% CI), p-value"), "ref", hrprintcrude, "ref", hrprintadj),
    cex = cexmy, adj = 0.5, bty = "n"
  )

  mtext("No. at risk", side = 1, line = 3.7, at = -550, adj = 0, cex = cexmy, font = 2)
  mtext(levs[1], side = 1, line = 4.7, at = -550, adj = 0, cex = cexmy, col = global_cols[1])
  mtext(levs[2], side = 1, line = 5.7, at = -550, adj = 0, cex = cexmy, col = global_cols[1])
  mtext(levs[3], side = 1, line = 6.7, at = -550, adj = 0, cex = cexmy, col = global_cols[4])
  mtext(levs[4], side = 1, line = 7.7, at = -550, adj = 0, cex = cexmy, col = global_cols[4])

  nrisk <- summary(fits, seq(0, 4) * 365, extend = T)
  nriskadj <- summary(fitsm, seq(0, 4) * 365, extend = T)

  axis(1,
    at = seq(0, 4) * 365, labels = nrisk$n.risk[nrisk$strata == "sos_lm_arni14=No"],
    line = 3.7, tick = FALSE, cex.axis = cexmy
  )
  axis(1,
    at = seq(0, 4) * 365, labels = nrisk$n.risk[nrisk$strata == "sos_lm_arni14=Yes"],
    line = 4.7, tick = FALSE, cex.axis = cexmy
  )
  axis(1,
    at = seq(0, 4) * 365, labels = nriskadj$n.risk[nriskadj$strata == "sos_lm_arni14=No"],
    line = 5.7, tick = FALSE, cex.axis = cexmy
  )
  axis(1,
    at = seq(0, 4) * 365, labels = nriskadj$n.risk[nriskadj$strata == "sos_lm_arni14=Yes"],
    line = 6.7, tick = FALSE, cex.axis = cexmy
  )
}
```

```{r kmss12, cache = cacheon, dependson="kmfuncss12", fig.cap = "KM/MCF - Substudy 1, 2 groups", fig.show='hold', out.width="50%", fig.subcap=c('CVD/First HFH', 'CVD', 'First HFH', 'CVD/Total HFH', 'Total HFH', 'All-cause mortality'), fig.ncol=2}

kmfunc(
  time = "sos_outtime_hosphf",
  event = "sos_out_deathcvhosphf",
  eventname = "CVD/First HFH",
  ymax = 0.8
)

kmfunc(
  time = "sos_outtime_death",
  event = "sos_out_deathcv",
  eventname = "CVD",
  ymax = 0.6
)

kmfunc(
  time = "sos_outtime_hosphf",
  event = "sos_out_hosphf",
  eventname = "First HFH",
  ymax = 0.6
)

kmfunc(
  event = "sos_out_deathcvhosphf",
  eventmod = "sos_out_countdeathcvhosphf",
  time = "sos_outtime_death",
  eventname = "CVD/HFH",
  ymax = 2.5,
  rep = T
)

kmfunc(
  event = "sos_out_hosphf",
  eventmod = "sos_out_counthosphf",
  time = "sos_outtime_death",
  eventname = "HFH",
  ymax = 2.5,
  rep = T
)

kmfunc(
  time = "sos_outtime_death",
  event = "sos_out_death",
  eventname = "All-cause mortality",
  ymax = 0.6
)
```
