```{r kmfuncss3, cache=cacheon}

kmfunc <- function(time, event, eventmod = NULL, eventname, ymax = 1, rep = FALSE) {
  fits <- survfit(formula(paste0("Surv(", time, ",", event, "== 'Yes') ~ shf_durationhf + sos_lm_arni14")),
    data = rsdata %>% filter(!is.na(shf_durationhf))
  )

  if (!rep) {
    # cox model
    amod <- with(imprsdatapop3, coxph(formula(paste0(
      "Surv(", time, ",", event, " == 'Yes') ~ sos_lm_arni14 * relevel(shf_durationhf, ref = '<6mo') +",
      paste(modvarspop3, collapse = " + ")
    ))))
    asmod <- summary(pool(amod))
    hrprinthf1 <- paste0(
      fn(exp(asmod$estimate[1]), dig = 2),
      " (", fn(exp(asmod$estimate[1] - global_z05 * asmod$std.error[1]), dig = 2),
      "-", fn(exp(asmod$estimate[1] + global_z05 * asmod$std.error[1]), dig = 2), "), ",
      fn(asmod$p.value[1], dig = 3, p = TRUE)
    )
    amod <- with(imprsdatapop3, coxph(formula(paste0(
      "Surv(", time, ",", event, " == 'Yes') ~ sos_lm_arni14 * relevel(shf_durationhf, ref = '>6mo') +",
      paste(modvarspop3, collapse = " + ")
    ))))
    asmod <- summary(pool(amod))
    hrprinthf2 <- paste0(
      fn(exp(asmod$estimate[1]), dig = 2),
      " (", fn(exp(asmod$estimate[1] - global_z05 * asmod$std.error[1]), dig = 2),
      "-", fn(exp(asmod$estimate[1] + global_z05 * asmod$std.error[1]), dig = 2), "), ",
      fn(asmod$p.value[1], dig = 3, p = TRUE)
    )
  }
  if (rep) {
    amod <- with(imprsdatapop3, glm.nb(formula(paste0(
      eventmod, " ~ sos_lm_arni14 * relevel(shf_durationhf, ref = '<6mo') + offset(log(sos_outtime_death)) +",
      paste(modvarspop1, collapse = " + ")
    ))))

    asmod <- summary(pool(amod))
    hrprinthf1 <- paste0(
      fn(exp(asmod$estimate[2]), dig = 2),
      " (", fn(exp(asmod$estimate[2] - global_z05 * asmod$std.error[2]), dig = 2),
      "-", fn(exp(asmod$estimate[2] + global_z05 * asmod$std.error[2]), dig = 2), "), ",
      fn(asmod$p.value[2], dig = 3, p = TRUE)
    )

    amod <- with(imprsdatapop3, glm.nb(formula(paste0(
      eventmod, " ~ sos_lm_arni14 * relevel(shf_durationhf, ref = '>6mo') + offset(log(sos_outtime_death)) +",
      paste(modvarspop1, collapse = " + ")
    ))))

    asmod <- summary(pool(amod))
    hrprinthf2 <- paste0(
      fn(exp(asmod$estimate[2]), dig = 2),
      " (", fn(exp(asmod$estimate[2] - global_z05 * asmod$std.error[2]), dig = 2),
      "-", fn(exp(asmod$estimate[2] + global_z05 * asmod$std.error[2]), dig = 2), "), ",
      fn(asmod$p.value[2], dig = 3, p = TRUE)
    )
    
    fitsr <- mcf(formula(paste0("Recur(sos_outtime, lopnr, ", event, " == 1) ~ shf_durationhf + sos_lm_arni14")),
      data = rsdatarec %>% filter(!is.na(shf_durationhf))
    )
  }

  # c(bottom, left, top, right)
  cexmy <- 1.2
  par(mar = c(8.5, 11, 1, 1.5) + 0.1)

  if (!rep) {
    plots <- plot(fits,
      fun = "event",
      ylab = paste0(eventname, " (%)"),
      yscale = 100,
      xscale = 365,
      col = rep(global_cols[c(2, 5)], 2),
      mark.time = FALSE,
      bty = "n",
      xlim = c(0, 365 * 4),
      ylim = c(0, ymax + 0.05),
      xlab = "Follow-up (years)",
      cex.lab = cexmy,
      axes = F,
      lwd = 2,
      lty = c(1, 1, 3, 3),
      xaxs = "i", yaxs = "i"
    )
    axis(2, seq(0, ymax + 0.05, 0.05), c(seq(0, ymax * 100, 5), 100), las = 2, cex.axis = cexmy)
    plotrix::axis.break(2, ymax + 0.025, style = "slash")
  }

  if (rep) {
    plot(
      fitsr@MCF$time[fitsr@MCF$sos_lm_arni14 == "No" & fitsr@MCF$shf_durationhf == "<6mo"],
      fitsr@MCF$MCF[fitsr@MCF$sos_lm_arni14 == "No" & fitsr@MCF$shf_durationhf == "<6mo"],
      type = "l",
      ylab = paste0("Mean cumulative ", eventname, " (per 100 patients)"),
      col = global_cols[2],
      xlim = c(0, 365 * 4),
      ylim = c(0, ymax + 0.05),
      xlab = "Follow-up (years)",
      cex.lab = cexmy,
      axes = F,
      lwd = 2,
      lty = 1,
      xaxs = "i", yaxs = "i"
    )
    lines(
      fitsr@MCF$time[fitsr@MCF$sos_lm_arni14 == "Yes" & fitsr@MCF$shf_durationhf == "<6mo"],
      fitsr@MCF$MCF[fitsr@MCF$sos_lm_arni14 == "Yes" & fitsr@MCF$shf_durationhf == "<6mo"],
      col = global_cols[5],
      lwd = 2,
      lty = 1
    )
    lines(
      fitsr@MCF$time[fitsr@MCF$sos_lm_arni14 == "No" & fitsr@MCF$shf_durationhf == ">6mo"],
      fitsr@MCF$MCF[fitsr@MCF$sos_lm_arni14 == "No" & fitsr@MCF$shf_durationhf == ">6mo"],
      col = global_cols[2],
      lwd = 2,
      lty = 3
    )
    lines(
      fitsr@MCF$time[fitsr@MCF$sos_lm_arni14 == "Yes" & fitsr@MCF$shf_durationhf == ">6mo"],
      fitsr@MCF$MCF[fitsr@MCF$sos_lm_arni14 == "Yes" & fitsr@MCF$shf_durationhf == ">6mo"],
      col = global_cols[5],
      lwd = 2,
      lty = 3
    )
    axis(2, seq(0, ymax, 0.5), seq(0, ymax * 100, 50), las = 2, cex.axis = cexmy)
  }

  axis(1, at = seq(0, 4) * 365, seq(0, 4), cex.axis = cexmy)

  levs <- c("HF <6 mo No ARNi", "HF <6 mo ARNi", "HF \u22656 mo No ARNi", "HF \u22656 mo ARNi")

  legend(
    x = 0.5, y = ymax + 0.05, bty = "n", c("", levs),
    col = c("white", global_cols[c(2, 5, 2, 5)]), cex = cexmy, lwd = 2, lty = c(1, 1, 1, 3, 3),
    text.col = c("white", global_cols[c(2, 5, 2, 5)])
  )
  legend(
    x = 2.35 * 365, y = ymax + 0.05, c("Adjusted HR (95% CI), p-value", "ref", hrprinthf1, "ref", hrprinthf2),
    cex = cexmy, adj = 0.5, bty = "n"
  )

  mtext("No. at risk", side = 1, line = 3.7, at = -550, adj = 0, cex = cexmy, font = 2)
  mtext(levs[1], side = 1, line = 4.7, at = -550, adj = 0, cex = cexmy, col = global_cols[2])
  mtext(levs[2], side = 1, line = 5.7, at = -550, adj = 0, cex = cexmy, col = global_cols[5])
  mtext(levs[3], side = 1, line = 6.7, at = -550, adj = 0, cex = cexmy, col = global_cols[2])
  mtext(levs[4], side = 1, line = 7.7, at = -550, adj = 0, cex = cexmy, col = global_cols[5])

  nrisk <- summary(fits, seq(0, 4) * 365, extend = T)

  axis(1,
    at = seq(0, 4) * 365, labels = nrisk$n.risk[nrisk$strata == "shf_durationhf=<6mo, sos_lm_arni14=No "],
    line = 3.7, tick = FALSE, cex.axis = cexmy
  )
  axis(1,
    at = seq(0, 4) * 365, labels = nrisk$n.risk[nrisk$strata == "shf_durationhf=<6mo, sos_lm_arni14=Yes"],
    line = 4.7, tick = FALSE, cex.axis = cexmy
  )
  axis(1,
    at = seq(0, 4) * 365, labels = nrisk$n.risk[nrisk$strata == "shf_durationhf=>6mo, sos_lm_arni14=No "],
    line = 5.7, tick = FALSE, cex.axis = cexmy
  )
  axis(1,
    at = seq(0, 4) * 365, labels = nrisk$n.risk[nrisk$strata == "shf_durationhf=>6mo, sos_lm_arni14=Yes"],
    line = 6.7, tick = FALSE, cex.axis = cexmy
  )
}
```

```{r kmcvdeathhfhss3, fig.cap="CVD/First HF hospitalization by HF duration - Substudy 3", cache=cacheon, dependson="kmfuncss3", fig.width=8, fig.height=7}
kmfunc(
  time = "sos_outtime_hosphf",
  event = "sos_out_deathcvhosphf",
  eventname = "CVD/First HFH",
  ymax = 0.6
)
```

```{r kmacvdeathss3, fig.cap="CVD by HF duration - Substudy 3", cache=cacheon, dependson="kmfuncss3", fig.width=8, fig.height=7}
kmfunc(
  time = "sos_outtime_death",
  event = "sos_out_deathcv",
  eventname = "CVD",
  ymax = 0.6
)
```

```{r kmhfhss3, fig.cap="First HF hospitalization by HF duration - Substudy 3", cache=cacheon, dependson="kmfuncss3", fig.width=8, fig.height=7}
kmfunc(
  time = "sos_outtime_hosphf",
  event = "sos_out_hosphf",
  eventname = "First HFH",
  ymax = 0.6
)
```

```{r kmtotcvdhfhss3, fig.cap="CVD/Total HF hospitalization - Substudy 3", cache=cacheon, dependson="kmfuncss3", fig.width=8, fig.height=7}
kmfunc(
  event = "sos_out_deathcvhosphf",
  eventmod = "sos_out_countdeathcvhosphf",
  time = "sos_outtime_death",
  eventname = "CVD/HFH",
  ymax = 2.5,
  rep = T
)
```

```{r kmtothfhss3, fig.cap="Total HF hospitalization by HF duration - Substudy 3", cache=cacheon, dependson="kmfuncss3", fig.width=8, fig.height=7}
kmfunc(
  event = "sos_out_hosphf",
  eventmod = "sos_out_counthosphf",
  time = "sos_outtime_death",
  eventname = "HFH",
  ymax = 2,
  rep = T
)
```

```{r kmdeathss3, fig.cap="All-cause mortality by HF duration - Substudy 3", cache=cacheon, dependson="kmfuncss3", fig.width=8, fig.height=7}
kmfunc(
  time = "sos_outtime_death",
  event = "sos_out_death",
  eventname = "All-cause mortality",
  ymax = 0.6
)
```
