```{r ortabss12, cache=cacheon}

# mult
ormod <- with(imprsdatapop1, glm(formula(paste0("sos_lm_arni14 == 'Yes' ~ ", paste(modvarspop1, collapse = " + "))),
  family = binomial(link = "logit")
))

sormod <- summary(pool(ormod))
nval <- length(sormod$term)

preds <- bind_cols(
  Variable = as.character(sormod$term[2:nval]),
  logor = sormod$estimate[2:nval],
  lci = sormod$estimate[2:nval] - global_z05 * sormod$std.error[2:nval],
  uci = sormod$estimate[2:nval] + global_z05 * sormod$std.error[2:nval],
  p = fn(sormod$p.value[2:nval], dig = 3, p = TRUE)
) %>%
  mutate(orci = paste0(
    fn(exp(logor), 2),
    " (", fn(exp(lci), 2), "-",
    fn(exp(uci), 2), ")"
  )) %>%
  select(Variable, logor, lci, uci, orci, p) %>%
  mutate(
    Variable = str_replace(Variable, fixed("Yes"), "")
  )

# crude
for (i in seq_along(modvarspop1)) {
  ormoduni <- with(imprsdatapop1, glm(formula(paste0("sos_lm_arni14 == 'Yes' ~ ", modvarspop1[i])),
    family = binomial(link = "logit")
  ))

  sormoduni <- summary(pool(ormoduni))
  nval <- length(sormoduni$term)

  predsunitmp <- bind_cols(
    Variable = as.character(sormoduni$term[2:nval]),
    logor = sormoduni$estimate[2:nval],
    lci = sormoduni$estimate[2:nval] - global_z05 * sormoduni$std.error[2:nval],
    uci = sormoduni$estimate[2:nval] + global_z05 * sormoduni$std.error[2:nval],
    p = fn(sormoduni$p.value[2:nval], dig = 3, p = TRUE)
  ) %>%
    mutate(orci = paste0(
      fn(exp(logor), 2),
      " (", fn(exp(lci), 2), "-",
      fn(exp(uci), 2), ")"
    )) %>%
    select(Variable, logor, lci, uci, orci, p) %>%
    mutate(
      Variable = str_replace(Variable, fixed("Yes"), "")
    )

  if (i == 1) {
    predsuni <<- predsunitmp
  } else {
    predsuni <<- bind_rows(predsuni, predsunitmp)
  }
}

predall <- full_join(predsuni,
  preds,
  by = "Variable"
)

predall <- predall %>%
  mutate(across(everything(), str_replace_all, fixed("Yes"), "")) %>%
  mutate(Variable = str_replace_all(Variable, "shf_sos_com_", "sos_com_"))

predall <- left_join(predall,
  meta_variables %>%
    select(variable, label),
  by = c("Variable" = "variable")
) %>%
  mutate(
    Variable = coalesce(label, Variable)
  ) %>%
  mutate(Variable = case_when(
    Variable == "shf_sexMale" ~ "Male vs female",
    Variable == "shf_age_cat>=75" ~ "Age (years) >=75 vs < 75",
    Variable == "shf_locationIn-patient" ~ "In-patient",
    Variable == "shf_followuplocation_catHospital" ~ "Follow-up hospital vs primary care/other",
    Variable == "shf_ef<30" ~ "EF (%) <30 vs 30-39",
    Variable == "shf_durationhf>6mo" ~ "Duration HF (months) >=6 vs <6",
    Variable == "shf_nyha_catIII-IV" ~ "NYHA class III-IV vs I-II",
    Variable == "shf_bmi_cat>=30" ~ "BMI (kg/m2) >=30 vs <30",
    Variable == "shf_map_cat>90" ~ "MAP >90 vs <=90",
    Variable == "shf_heartrate_cat>70" ~ "Heart rate (beats/min) >70 vs <=70",
    Variable == "shf_gfrckdepi_cat<60" ~ "eGFR (mL/min/1.73 m²) <60 vs >=60",
    Variable == "shf_potassium_cathyperkalemia" ~ "Hyperkalemia vs normakalemia",
    Variable == "shf_potassium_cathypokalemia" ~ "Hypokalemia vs normakalemia",
    Variable == "shf_ntprobnp_cat>=median" ~ "NT-proBNP (pg/ml) >=median vs <median",
    Variable == "shf_device_catCRT/ICD" ~ "CRT/ICD",
    Variable == "scb_famtypeLiving alone" ~ "Living alone vs cohabitating",
    Variable == "scb_educationSecondary school" ~ "Secondary vs compulsory school",
    Variable == "scb_educationUniversity" ~ "University vs compulsory school",
    Variable == "scb_dispincome_cat>=median" ~ "Income >=median vs <median",
    Variable == "shf_indexyear" ~ "Year of inclusion",
    Variable == "sos_lm_previousrasi" ~ "Previous ACEi/ARB",
    Variable == "sos_timeprevhosphf_cat2<=365" ~ "Previous HFH (days) <=365 vs No", 
    Variable == "sos_timeprevhosphf_cat2>365" ~ "Previous HFH (days) >365 vs No", 
    TRUE ~ Variable
  ))

predallprint <- predall %>%
  select(Variable, "orci.x", "p.x", "orci.y", "p.y")

colnames(predallprint) <- c("Variable", rep(c("OR (95% CI)", "p-value"), 2))

write.xlsx(predallprint, paste0(
  "./output/tabs/Associations between ARNi use and characteristics_substudy12_", Sys.Date(), ".xlsx"
), rowNames = FALSE, overwrite = TRUE)

default_kable(predallprint,
  font_size = 6,
  caption = "Associations between ARNi use and characteristics - Substudy 1, 2 groups",
  escape = T
) %>%
  add_header_above(c(" " = 1, "Crude" = 2, "Adjusted" = 2))
```

```{r orforestss12, cache=cacheon, dependson=c("ortabss12"), fig.width=5, fig.height=10, fig.cap="Adjusted associations between ARNi use and characteristics - Substudy 1, 2 groups"}

forestdata <- predall %>%
  mutate(across(c("logor.y", "lci.y", "uci.y"), as.numeric)) %>%
  select(Variable, ends_with(".y"))

colnames(forestdata) <- str_remove_all(colnames(forestdata), ".y")

cextext <- 0.9

forestdata <- forestdata %>%
  mutate(
    Variable = str_replace_all(Variable, ">=", "\u2265"),
    Variable = str_replace_all(Variable, "<=", "\u2264")
  ) %>%
  arrange(logor) %>%
  mutate(
    order = n():1 - 1,
    pnum = as.numeric(p),
    cols = if_else(is.na(p) | p < 0.05, global_cols[1], global_cols[5])
  )

minmy <- round(exp(min(forestdata$lci, na.rm = T)), 2)
maxmy <- ceiling(exp(max(forestdata$uci, na.rm = T)))

# c(bottom, left, top, right)
par(mar = c(4, 20, 0, 0.5) + 0.2)

gplots::plotCI(
  x = forestdata$logor, y = forestdata$order,
  li = forestdata$lci,
  ui = forestdata$uci,
  err = "x",
  cex = 0.7,
  xlim = c(
    log(minmy),
    log(maxmy)
  ),
  xlab = "",
  ylim = c(1, nrow(forestdata) - 1),
  axes = FALSE,
  ylab = "",
  main = NA,
  pch = 22,
  pt.bg = forestdata$cols,
  col = forestdata$cols,
  lwd = .9,
  gap = 0,
  sfrac = 0.004
)

abline(v = log(1), lty = 2)

axis(1,
  cex.axis = cextext, at = log(c(minmy, 1, maxmy)),
  labels = c(minmy, 1, maxmy), gap.axis = 0.000001
)

axis(2,
  at = forestdata$order,
  labels = forestdata$Variable,
  cex.axis = cextext, tick = FALSE, las = 2, line = 19, hadj = 0
)

axis(2,
  at = nrow(forestdata),
  labels = "Adjusted OR (95% CI)",
  cex.axis = cextext, tick = FALSE, las = 2, line = 2, hadj = 0.5, font = 2
)
axis(2,
  at = forestdata$order,
  labels = forestdata$orci,
  cex.axis = cextext, tick = FALSE, las = 2, line = 2, hadj = 0.5
)

axis(1,
  at = (log(maxmy) + log(minmy)) / 2, cex.axis = cextext,
  labels = "Adjusted OR\n(95% CI)", line = 2, tick = FALSE
)
```
