```{r ortabss13, cache=cacheon}

orfunc <- function(impdata, level) {
  # mult
  ormod <- with(impdata, glm(
    formula(paste0(
      "sos_lm_arni3 == '", level, "' ~ ",
      paste(modvarspop1, collapse = " + ")
    )),
    family = binomial(link = "logit")
  ))

  sormod <- summary(pool(ormod))
  nval <- length(sormod$term)

  preds <- bind_cols(
    Variable = as.character(sormod$term[2:nval]),
    logoradj = sormod$estimate[2:nval],
    lciadj = sormod$estimate[2:nval] - global_z05 * sormod$std.error[2:nval],
    uciadj = sormod$estimate[2:nval] + global_z05 * sormod$std.error[2:nval],
    padj = fn(sormod$p.value[2:nval], dig = 3, p = TRUE)
  ) %>%
    mutate(orciadj = paste0(
      fn(exp(logoradj), 2),
      " (", fn(exp(lciadj), 2), "-",
      fn(exp(uciadj), 2), ")"
    )) %>%
    select(Variable, logoradj, lciadj, uciadj, orciadj, padj) %>%
    mutate(
      Variable = str_replace(Variable, fixed("Yes"), "")
    )

  # crude
  for (i in seq_along(modvarspop1)) {
    ormoduni <- with(impdata, glm(
      formula(paste0(
        "sos_lm_arni3 == '", level,
        "' ~ ", modvarspop1[i]
      )),
      family = binomial(link = "logit")
    ))

    sormoduni <- summary(pool(ormoduni))
    nval <- length(sormoduni$term)

    predsunitmp <- bind_cols(
      Variable = as.character(sormoduni$term[2:nval]),
      logorcrude = sormoduni$estimate[2:nval],
      lcicrude = sormoduni$estimate[2:nval] - global_z05 * sormoduni$std.error[2:nval],
      ucicrude = sormoduni$estimate[2:nval] + global_z05 * sormoduni$std.error[2:nval],
      pcrude = fn(sormoduni$p.value[2:nval], dig = 3, p = TRUE)
    ) %>%
      mutate(orcicrude = paste0(
        fn(exp(logorcrude), 2),
        " (", fn(exp(lcicrude), 2), "-",
        fn(exp(ucicrude), 2), ")"
      )) %>%
      select(Variable, logorcrude, lcicrude, ucicrude, orcicrude, pcrude) %>%
      mutate(
        Variable = str_replace(Variable, fixed("Yes"), "")
      )

    if (i == 1) {
      predsuni <<- predsunitmp
    } else {
      predsuni <<- bind_rows(predsuni, predsunitmp)
    }
  }

  predall <- full_join(predsuni,
    preds,
    by = "Variable"
  )
}


imprsdatapop131 <- miceadds::subset_datlist(imprsdata,
  expr_subset = rsdata$pop13 & rsdata$sos_lm_arni3 != "15-90 days"
)
imprsdatapop132 <- miceadds::subset_datlist(imprsdata,
  expr_subset = rsdata$pop13 & rsdata$sos_lm_arni3 != "0-14 days"
)

pred1 <- orfunc(impdata = imprsdatapop131, level = "0-14 days")
colnames(pred1) <- paste0(colnames(pred1), "_1")
pred2 <- orfunc(imprsdatapop132, "15-90 days")
colnames(pred2) <- paste0(colnames(pred2), "_2")

predall <- cbind(pred1, pred2 %>% select(-Variable_2)) %>%
  rename(Variable = Variable_1)

predall <- predall %>%
  mutate(across(everything(), str_replace_all, fixed("Yes"), "")) %>%
  mutate(Variable = str_replace_all(Variable, "shf_sos_com_", "sos_com_"))

predall <- left_join(predall,
  meta_variables %>%
    select(variable, label),
  by = c("Variable" = "variable")
) %>%
  mutate(
    Variable = coalesce(label, Variable)
  ) %>%
  mutate(Variable = case_when(
    Variable == "shf_sexMale" ~ "Male vs female",
    Variable == "shf_age_cat>=75" ~ "Age (years) >=75 vs < 75",
    Variable == "shf_locationIn-patient" ~ "In-patient",
    Variable == "shf_followuplocation_catHospital" ~ "Follow-up hospital vs primary care/other",
    Variable == "shf_ef<30" ~ "EF (%) <30 vs 30-39",
    Variable == "shf_durationhf>6mo" ~ "Duration HF (mo) >=6 vs <6",
    Variable == "shf_nyha_catIII-IV" ~ "NYHA class III-IV vs I-II",
    Variable == "shf_bmi_cat>=30" ~ "BMI (kg/m2) >=30 vs <30",
    Variable == "shf_map_cat>90" ~ "MAP >90 vs <=90",
    Variable == "shf_heartrate_cat>70" ~ "Heart rate (beats/min) >70 vs <=70",
    Variable == "shf_gfrckdepi_cat<60" ~ "eGFR (mL/min/1.73 m²) <60 vs >=60",
    Variable == "shf_potassium_cathyperkalemia" ~ "Hyperkalemia vs normakalemia",
    Variable == "shf_potassium_cathypokalemia" ~ "Hypokalemia vs normakalemia",
    Variable == "shf_ntprobnp_cat>=median" ~ "NT-proBNP (pg/ml) >=median vs <median",
    Variable == "shf_device_catCRT/ICD" ~ "CRT/ICD",
    Variable == "scb_famtypeLiving alone" ~ "Living alone vs cohabitating",
    Variable == "scb_educationSecondary school" ~ "Secondary vs compulsory school",
    Variable == "scb_educationUniversity" ~ "University vs compulsory school",
    Variable == "scb_dispincome_cat>=median" ~ "Income >=median vs <median",
    Variable == "shf_indexyear" ~ "Year of inclusion",
    Variable == "sos_lm_previousrasi" ~ "Previous ACEi/ARB",
    Variable == "sos_timeprevhosphf_cat2<=365" ~ "Previous HFH (days) <=365 vs No", 
    Variable == "sos_timeprevhosphf_cat2>365" ~ "Previous HFH (days) >365 vs No", 
    TRUE ~ Variable
  ))

predallprint <- predall %>%
  select(Variable, "orcicrude_1", "pcrude_1", "orcicrude_2", "pcrude_2", "orciadj_1", "padj_1", "orciadj_2", "padj_2")

colnames(predallprint) <- c("Variable", rep(c("OR (95% CI)", "p-value"), 4))

write.xlsx(predallprint, paste0(
  "./output/tabs/Associations between ARNi use and characteristics_substudy13_", Sys.Date(), ".xlsx"
), rowNames = FALSE, overwrite = TRUE)

default_kable(predallprint,
  font_size = 6,
  caption = "Associations between ARNi use and characteristics - Substudy 1, 3 groups",
  escape = T
) %>%
  add_header_above(c(" " = 1, "0-14 days vs >90/No" = 2, "15-90 days vs >90/No" = 2, 
                     "0-14 days vs >90/No" = 2, "15-90 days vs >90/No" = 2)) %>%
  add_header_above(c(" " = 1, "Crude" = 4, "Adjusted" = 4))
```

\clearpage

```{r orforestss13, cache=cacheon, dependson=c("ortabss13"), fig.width=5, fig.height=10, fig.cap="Adjusted associations between ARNi use and characteristics - Substudy 1, 3 groups"}

forestdata <- predall %>%
  select(Variable, contains("adj")) %>%
  mutate(across(contains(c("logor", "lci", "uci")), as.numeric))

forestdata <- forestdata %>%
  mutate(
    Variable = str_replace_all(Variable, ">=", "\u2265"),
    Variable = str_replace_all(Variable, "<=", "\u2264")
  ) %>%
  mutate(
    order = n():1 - 1,
    p_1num = as.numeric(padj_1),
    p_2num = as.numeric(padj_2),
    cols_1 = if_else(is.na(p_1num) | p_1num < 0.05, global_cols[1], global_cols[5]),
    cols_2 = if_else(is.na(p_2num) | p_2num < 0.05, global_cols[1], global_cols[5]),
  )

minmy <- round(exp(min(c(forestdata$lciadj_1, forestdata$lciadj_2), na.rm = T)), 2)
maxmy <- ceiling(exp(max(c(forestdata$uciadj_1, forestdata$uciadj_2), na.rm = T)))

add1 <- 6.5
cextext <- 0.6

# c(bottom, left, top, right)
par(mar = c(3, 18, 0, 0) + 0.2)

gplots::plotCI(
  x = forestdata$logoradj_1, y = forestdata$order,
  li = forestdata$lciadj_1,
  ui = forestdata$uciadj_1,
  err = "x",
  cex = 0.4,
  xlim = c(
    log(minmy),
    log(maxmy) + add1
  ),
  xlab = "",
  ylim = c(1, nrow(forestdata)),
  axes = FALSE,
  ylab = "",
  main = NA,
  pch = 22,
  pt.bg = forestdata$cols_1,
  col = forestdata$cols_1,
  lwd = .4,
  gap = 0,
  sfrac = 0.001
)

gplots::plotCI(
  add = TRUE,
  x = forestdata$logoradj_2 + add1,
  y = forestdata$order,
  li = forestdata$lciadj_2 + add1,
  ui = forestdata$uciadj_2 + add1,
  err = "x",
  cex = 0.4,
  pch = 22,
  pt.bg = forestdata$cols_2,
  col = forestdata$cols_2,
  lwd = .4,
  gap = 0,
  sfrac = 0.001
)

abline(v = log(1), lty = 3, col = "grey")
abline(v = log(1) + add1, lty = 3, col = "grey")

axis(1,
  cex.axis = cextext, at = log(c(minmy, 1, maxmy)),
  labels = c(minmy, 1, maxmy), gap.axis = 0.000001
)
axis(1,
  cex.axis = cextext, at = log(c(minmy, 1, maxmy)) + add1,
  labels = c(minmy, 1, maxmy), gap.axis = 0.000001
)

axis(2,
  at = forestdata$order,
  labels = forestdata$Variable,
  cex.axis = cextext, tick = FALSE, las = 2, line = 17, hadj = 0
)

axis(2,
  at = nrow(forestdata),
  labels = "0-14 vs >90/No",
  cex.axis = cextext, tick = FALSE, las = 2, line = 5.5, hadj = 0.5, font = 2
)
axis(2,
  at = forestdata$order,
  labels = forestdata$orciadj_1,
  cex.axis = cextext, tick = FALSE, las = 2, line = 5.5, hadj = 0.5
)
axis(2,
  at = nrow(forestdata),
  labels = "15-90 vs >90/No",
  cex.axis = cextext, tick = FALSE, las = 2, line = 1, hadj = 0.5, font = 2
)
axis(2,
  at = forestdata$order,
  labels = forestdata$orciadj_2,
  cex.axis = cextext, tick = FALSE, las = 2, line = 1, hadj = 0.5
)

axis(2,
  at = nrow(forestdata) + 1,
  labels = "Adjusted OR (95% CI)",
  cex.axis = cextext, tick = FALSE, las = 2, line = (5.5 + 1) / 2, hadj = 0.5, font = 2
)

axis(1,
  at = (log(maxmy) + log(minmy)) / 2 + add1 / 2, cex.axis = cextext,
  labels = "Adjusted OR (95% CI)", line = 1, tick = FALSE
)
```
