```{r overtimenpr, cache = cacheon, fig.cap = "ARNi overtime - Substudy 2, NPR population"}

cexmy <- 1.5
# c(bottom, left, top, right) default c(5, 4, 4, 2) + 0.1.
par(mar = c(4, 5, .5, 0.5) + 0.1)

overtimenpr <- nprdata %>%
  count(shf_indexyear) %>%
  mutate(
    pop = "All"
  ) %>%
  mutate(count = 1:n())

overtimelocation <- nprdata %>%
  group_by(sos_location) %>%
  count(shf_indexyear) %>%
  mutate(
    count = 1:n(),
    pop = as.factor(sos_location)
  ) %>%
  ungroup()

plot(overtimenpr %>% pull(count),
  overtimenpr %>% pull(n),
  type = "b",
  pch = 19,
  lty = 1,
  col = global_cols[1],
  lwd = 3,
  cex = 1.5,
  axes = FALSE,
  ylim = c(0, 900),
  xlim = c(1, max(overtimenpr$count) + .1),
  ylab = "",
  xlab = "Year",
  cex.lab = cexmy
)
matplot(overtimelocation %>% filter(pop == "In-patient") %>% pull(count),
  overtimelocation %>% filter(pop == "In-patient") %>% pull(n),
  type = "b",
  pch = 19,
  lty = 1,
  col = global_cols[3],
  lwd = 3,
  cex = 1.5,
  add = T
)
matplot(overtimelocation %>% filter(pop == "Out-patient") %>% pull(count),
  overtimelocation %>% filter(pop == "Out-patient") %>% pull(n),
  type = "b",
  pch = 19,
  lty = 1,
  col = global_cols[5],
  lwd = 3,
  cex = 1.5,
  add = T
)

legend(
  "topleft", c("Overall", "In-patient", "Out-patient"),
  col = global_cols[c(1, 3, 5)], lwd = 2, pch = 19, bty = "n",
  cex = cexmy
)

axis(1, c(0, overtimenpr %>% pull(count)),
  c(NA, overtimenpr %>% pull(shf_indexyear)),
  cex.axis = cexmy
)

axis(2, at = 450, line = 2.5, label = "Count", cex.axis = cexmy, tick = FALSE)
axis(2, c(-100, seq(0, 900, 100)), c(NA, seq(0, 900, 100)), las = 2, cex.axis = cexmy)
```

```{r overtimetabnpr, cache = cacheon}

overtimenprtab <- bind_rows(
  overtimenpr,
  overtimelocation
) %>%
  select(shf_indexyear, pop, n) %>%
  rename(Year = shf_indexyear) %>%
  arrange(Year, pop) %>%
  pivot_wider(names_from = pop, values_from = n)

default_kable(overtimenprtab, caption = "Numbers for Figure", scale_down = F)
```
